name: On Pull Request

on:
  pull_request:
    branches:
      - main
      - release/*
    types:
      - ready_for_review
      - opened
      - reopened
      - synchronize

jobs:
  test:
    uses: ./.github/workflows/test.yml
  test-demo-apps:
    uses: ./.github/workflows/test_demo_apps.yml